# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export DOTFILES="${HOME}/dotfiles"
export DOTZSH="${DOTFILES}/zsh"
export ZSH="${DOTFILES}/oh-my-zsh"

# Load PATH early so plugins can find executables
[ -f "${DOTZSH}/zsh_path.zsh" ] && source "${DOTZSH}/zsh_path.zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="steeef"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=45

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  asdf
  battery
  brew
  docker-compose
  #docker-machine
  dotenv
  git
  history
  history-substring-search
  iterm2
  #jsontools
  #kubectl
  macos
  #pip
  #python
  ssh-agent
  sudo
  tig
  tmux
  urltools
  vi-mode
)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Configure global environment
export LANG=en_US.UTF-8
export EDITOR='vim'

# Load custom config files
[ -f "${DOTZSH}/zsh_config.zsh" ] && source "${DOTZSH}/zsh_config.zsh"
[ -f "${DOTZSH}/zsh_alias.zsh" ] && source "${DOTZSH}/zsh_alias.zsh"
[ -f "${DOTZSH}/zsh_env.zsh" ] && source "${DOTZSH}/zsh_env.zsh"
[ -f "${DOTZSH}/zsh_env.zsh.local" ] && source "${DOTZSH}/zsh_env.zsh.local"
[ -f "${DOTZSH}/zsh_completions.zsh" ] && source "${DOTZSH}/zsh_completions.zsh"
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load Google Cloud SDK paths and completions
if [ -d "${HOME}/google-cloud-sdk" ]; then
  [ -f "${HOME}/google-cloud-sdk/path.zsh.inc" ] && . "${HOME}/google-cloud-sdk/path.zsh.inc"
  [ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ] && . "${HOME}/google-cloud-sdk/completion.zsh.inc"
fi

if [ -d '/usr/local/google/home/alanblount/google-cloud-sdk' ]; then
  [ -f '/usr/local/google/home/alanblount/google-cloud-sdk/path.zsh.inc' ] && . '/usr/local/google/home/alanblount/google-cloud-sdk/path.zsh.inc'
  [ -f '/usr/local/google/home/alanblount/google-cloud-sdk/completion.zsh.inc' ] && . '/usr/local/google/home/alanblount/google-cloud-sdk/completion.zsh.inc'
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Configure g4d completions if present
[[ ! -f /etc/bash_completion.d/g4d ]] || source /etc/bash_completion.d/g4d
# Configure glinux custom files if present
[[ ! -f "${DOTZSH}/glinux.sh" ]] || source "${DOTZSH}/glinux.sh"

fixup_ssh_auth_sock() {
  if [[ -n ${SSH_AUTH_SOCK} && ! -e ${SSH_AUTH_SOCK} ]]; then
    local new_sock=$(echo /tmp/ssh-*/agent.*(-UNom[1]))
    if [[ -n ${new_sock} ]]; then
      export SSH_AUTH_SOCK=${new_sock}
    fi
  fi
}

# Run before each command
autoload -U add-zsh-hook
add-zsh-hook preexec fixup_ssh_auth_sock

# Or, alias gcert to run the fixup first
gcert() {
  fixup_ssh_auth_sock
  command gcert "$@"
}

# Auto-switch gcloud config on directory change
load-gcloud-config() {
  if [[ -f .gcloud-config ]]; then
    local conf=$(cat .gcloud-config)
    export CLOUDSDK_ACTIVE_CONFIG_NAME="$conf"
    echo "☁️ gcloud: $conf"
  else
    # Optional: unset to revert to default when leaving the folder
    unset CLOUDSDK_ACTIVE_CONFIG_NAME
  fi
}
add-zsh-hook chpwd load-gcloud-config
load-gcloud-config # run once on startup

# Added by Antigravity
export PATH="/Users/alanblount/.antigravity/antigravity/bin:$PATH"

# opencode
export PATH=/Users/alanblount/.opencode/bin:$PATH
